sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: j1+qzk6MQ7GH2TTgHzLY9HZTH+IoFXGRFlLJWS3Sr+EYH4JpCBG7GvOGUX4BJ75ZAao/6p5zRVvI7IFPZc85O54zSxbjIkXiVwDK6jcd0cfQr7bLOCjWfpDsX3VHmbGmkKuko7Z2/qF8f5tCkh5cRkv53juzMZvdQZydunn4AFTy8tOGBMcPasNsdJcJAjI0Oq5dpJgT4f9j23qjNFiBoXcEBTv4mhYc5C3SMMyBhnIgXd/jK2si7vYVhyCiWUAswZswhibcpS0XVCL5hI3Lxnkv08dpUhaBkp0A55drgRkk+6ih0D9fty5nKE1Ajc7UVqp7bXpHEws/jgISksWQU7J4lo9cIp8L/s5+DiwtorTjPha7YGHgHdgxMfDARiJmCD+LKkqVv79H1nD7fCsXUXosZaxidUQ/V79Jjf06EoU6yzcPXKiokGwZQ33FrMYEsB34A+ZXxDhVuFL5qb2s5h+w4ibF5K7roIwuDP4/R6p9sq2FWbPxqzdRhkczaHFbjNzcluZ/2r8t6MTKd9EkrwFAhjCH0JPHYecwXEQ66kF9gB7YGDDrMVhsAKGi+Ao9Fa8/Q2WC9rUUx7PDCvTDziX84MxHF9hZZbHZ/J6frWFgmmxAOOZl71h3hh6I9EYi74YoOUhvEPGxwbHLVOJy39a9+A4cFb9iTuyhcA/meqs=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/The-Physiology-of-Marriage-Part-3_5958
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy